channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - pytorch::pytorch
  - colabfold
  - openmm>=8
  - pdbfixer
  - mdtraj
  - numpy<2
  - scikit-learn
  - typer
  - numba
  - natsort
